import React from 'react';

const Navigation: React.FC = () => {
  return (
    <nav>
      <ul>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
        <li>asda</li>
      </ul>
    </nav>
  );
};

export default Navigation;
